Repository bob-crutchley/courseware, pull requests merged in 2019-12, with the labels that each got.

#512 Azure Container Instances - closes #511
  state.json
  topics/README.md
  topics/azure/README.md
  topics/azure/modules/container-instances/README.md
Labels: 0.0.12, merged-to-dev

#514 Ansible Introduction Typo - closes #493
  state.json
  topics/ansible/modules/introduction/README.md
Labels: 0.0.12, review-complete

#460 Cloud common - Infrastructure-as-a-Service (IaaS) closes #185
  state.json
  topics/cloud/README.md
  topics/cloud/modules/infrastructure-as-a-service/README.md
Labels: 0.0.12, merged-to-dev

#461 Cloud common - Platform-as-a-Service (PaaS) closes #186
  state.json
  topics/cloud/README.md
  topics/cloud/modules/infrastructure-as-a-service/README.md
  topics/cloud/modules/platform-as-a-service/README.md
Labels: 0.0.12, merged-to-dev

#462 Cloud common - Software-as-a-Service (SaaS) closes #187
  state.json
  topics/cloud/README.md
  topics/cloud/modules/software-as-a-service/README.md
Labels: 0.0.12, merged-to-dev

#463 Cloud common - compare and contrast the three different service types (IaaS, PaaS, SaaS) closes 188
  state.json
  topics/cloud/README.md
  topics/cloud/modules/iaas-paas-saas/README.md
Labels: 0.0.12, merged-to-dev

#466 Cloud common - describe Public cloud closes #189
  state.json
  topics/cloud/README.md
  topics/cloud/modules/public-cloud/README.md
Labels: 0.0.12, review-required

#467 Cloud common - describe Private cloud closes #190
  state.json
  topics/cloud/README.md
  topics/cloud/modules/private-cloud/README.md
Labels: 0.0.12, merged-to-dev

#472 Cloud common - describe Hybrid cloud closes #191
  state.json
  topics/cloud/README.md
  topics/cloud/modules/hybrid-cloud/README.md
Labels: 0.0.12, review-complete

#418 Networking IP Module - closes #415
  state.json
  topics/networking/README.md
  topics/networking/modules/ip/README.md
Labels: 0.0.12, review-complete

#499 Networking Gateways Module closes #498
  state.json
  topics/networking/README.md
  topics/networking/modules/gateways/README.md
  topics/networking/modules/ip/README.md
Labels: 0.0.12, review-complete

#479 Cloud common - security in the cloud closes #478
  state.json
  topics/cloud/README.md
  topics/cloud/modules/cloud-security/README.md
  topics/networking/modules/ip/README.md
Labels: 0.0.12, review-complete

#497 Networking Localhost and Ports Module closes #495
  state.json
  topics/networking/README.md
  topics/networking/modules/localhost-and-ports/README.md
Labels: 0.0.12, merged-to-dev

#503 Networking Routing Module closes #501
  state.json
  topics/networking/README.md
  topics/networking/modules/ip-routing/README.md
Labels: 0.0.12, merged-to-dev

#475 Cloud common - describe Regions and Availability Zones closes #193
  state.json
  topics/cloud/README.md
  topics/cloud/modules/regions-and-availability-zone/README.md
Labels: 0.0.12, merged-to-dev

#477 Updating contributing readme file with additional instructions closes #476
  CONTRIBUTING.md
  state.json
Labels: 0.0.13, merged-to-dev

#530 Jenkins Python Systemd Module Rework - closes #526
  topics/jenkins/README.md
  topics/jenkins/modules/basic-python-flask-freestyle-project-deployment-with-systemd/README.md
  topics/jenkins/modules/basic-python-flask-freestyle-project-deployment-with-systemd/flask-app.service
  topics/jenkins/modules/python-flask-freestyle-project/README.md
  topics/jenkins/modules/python-flask-freestyle-project/resources/app.py
  topics/jenkins/modules/python-flask-freestyle-project/resources/flask-app.service
  topics/jenkins/modules/python-flask-freestyle-project/resources/requirements.txt
Labels: review-complete
