Repository bob-crutchley/courseware, pull requests merged in 2019-08, with the labels that each got.

#17 Implementing #16
  .circleci/config.yml
  automation/topics.py
  topics/README.md
  topics/aws/README.md
  topics/git/README.md
Labels: enhancement

#19 Linux - Managing systemd Services #18
  topics/README.md
  topics/linux/README.md
  topics/linux/modules/managing-systemd-services/README.md
Labels: enhancement

#21 Added a state file - closes #20
  .circleci/config.yml
  .gitignore
  automation/functions.py
  automation/state.py
  state.json
  topics/git/modules/basics/README.md
  topics/groovy/modules/variables/README.md
Labels: enhancement

#23 Basic Python Flask systemd Deployment - closes #22
  topics/jenkins/README.md
  topics/jenkins/modules/basic-python-flask-freestyle-project-deployment-with-systemd/README.md
  topics/jenkins/modules/basic-python-flask-freestyle-project-deployment-with-systemd/app.py
  topics/jenkins/modules/basic-python-flask-freestyle-project-deployment-with-systemd/flask-app.service
  topics/jenkins/modules/basic-python-flask-freestyle-project-deployment-with-systemd/requirements.txt
Labels: enhancement

#26 Linux sudoers Module - closes #24
  state.json
  topics/linux/README.md
  topics/linux/modules/sudoers/README.md
Labels: enhancement

#27 modules.py script clean up - closes #8
  automation/modules.py
  topics/aws/README.md
  topics/git/README.md
  topics/groovy/README.md
  topics/jenkins/README.md
Labels: enhancement

#39 GitHub README needed updating
  state.json
  topics/aws/README.md
  topics/git/README.md
  topics/groovy/README.md
  topics/jenkins/README.md
  topics/linux/README.md
Labels: enhancement

#45 Changes to Git revert and tasks
  state.json
  topics/aws/README.md
  topics/git/README.md
  topics/git/modules/reverting/README.md
  topics/groovy/README.md
  topics/jenkins/README.md
  topics/linux/README.md
Labels: bug

#52 Fix modules.py - closes #51
  automation/modules.py
  state.json
  topics/aws/README.md
  topics/git/README.md
  topics/groovy/README.md
  topics/jenkins/README.md
  topics/linux/README.md
Labels: bug

#54 updated main readme - closes #53
  README.md
  state.json
Labels: documentation

#31 Issue 10 - closes 10
  state.json
  topics/README.md
  topics/markdown/README.md
  topics/markdown/modules/advanced/README.md
  topics/markdown/modules/advanced/project/README.md
  topics/markdown/modules/advanced/project/pass_gen.py
  topics/markdown/modules/advanced/project/pip_dependencies.txt
  topics/markdown/modules/basics/README.md
  topics/markdown/modules/links_images/README.md
Labels: enhancement

#81 Netcat Topic - closes #77
  state.json
  topics/README.md
  topics/netcat/README.md
  topics/netcat/modules/port-scanning/README.md
Labels: enhancement

#55 Networking Topic & MAC Address Module - closes #50
  state.json
  topics/README.md
  topics/networking/README.md
  topics/networking/modules/mac-address/README.md
Labels: enhancement

#84 Implemented the first course - closes #83
  .circleci/config.yml
  automation/course.py
  automation/functions.py
  courses/networking/README.md
  state.json
  topics/netcat/modules/port-scanning/README.md
  topics/networking/modules/mac-address/README.md
Labels: enhancement

#85 port scanning with netcat - closes #78
  courses/networking/README.md
  state.json
  topics/netcat/README.md
  topics/netcat/modules/port-scanning/README.md
Labels: enhancement
